# Generated by Django 2.2.3 on 2019-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funccrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('일반', '일반'), ('공지', '공지'), ('과제', '과제')], default='일반', max_length=20),
        ),
    ]
